version: '3' 
services: 
  influxdb: 
    image: influxdb
    ports: 
      - 8086:8086
      - 8088:8088
    volumes: 
      - ./digital_twin/data_access/influxdbserver/influxdb:/var/lib/influxdb/
    networks: 
       - app-network
  rabbitmq: 
    image: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
      - 1883:1883
    networks: 
       - app-network
  incubator: 
    image: incubator
    networks: 
       - app-network
networks:
  app-network:
    driver: bridge
